#######################################################
#               SEO RELATED VARIABLES
#######################################################
title: "GamePlan"              

description: "GamePlan is the best Gantt Chart software because it's visual. Draw the project workflow and the Gantt chart is automatically created! No one else does this!"        # A short description in default language

url: ""                # The full URL to your site. 
# baseurl: /gameplan-website                       
  
twitter:
  username: gameplan2015   # site-wide Twitter handle

logo: '/assets/images/gameplan_logo.png'                 

social:
  name: GamePlan
  links:
    - https://www.facebook.com/gameplan2015/
    - https://twitter.com/gameplan2015
    - https://www.youtube.com/channel/UCODk0c1AkMOoz68Di3VGEqg
    - https://www.linkedin.com/company/gameplan-global-solutions-inc-

lang: en_US

######################################################
include: ["_pages"]


# sass style can be nested (default), compact, compressed, or expanded.
sass:
    load_paths:
        - _sass
        - node_modules
    style: compressed

collections:
  solutions:
    output: true

plugins:
  - jekyll-toc
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

permalink: /:categories/:title

exclude:
  - vendor
  - deploy.sh
  - node_modules
  - Makefile
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - packages.json
